admin_categoria_index:
    path:     /
    defaults: { _controller: "RedesSivelBundle:Categoria:index" }
    methods:  GET

admin_categoria_show:
    path:     /{id}/show
    defaults: { _controller: "RedesSivelBundle:Categoria:show" }
    methods:  GET

admin_categoria_new:
    path:     /new
    defaults: { _controller: "RedesSivelBundle:Categoria:new" }
    methods:  [GET, POST]

admin_categoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "RedesSivelBundle:Categoria:edit" }
    methods:  [GET, POST]

admin_categoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "RedesSivelBundle:Categoria:delete" }
    methods:  DELETE
