admin_comentarios_index:
    path:     /
    defaults: { _controller: "RedesSivelBundle:Comentario:index" }
    methods:  GET

admin_comentarios_show:
    path:     /{id}/show
    defaults: { _controller: "RedesSivelBundle:Comentario:show" }
    methods:  GET

admin_comentarios_new:
    path:     /new
    defaults: { _controller: "RedesSivelBundle:Comentario:new" }
    methods:  [GET, POST]

admin_comentarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "RedesSivelBundle:Comentario:edit" }
    methods:  [GET, POST]

admin_comentarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "RedesSivelBundle:Comentario:delete" }
    methods:  DELETE
