admin_unidad_index:
    path:     /
    defaults: { _controller: "RedesSivelBundle:UnidadMedida:index" }
    methods:  GET

admin_unidad_show:
    path:     /{id}/show
    defaults: { _controller: "RedesSivelBundle:UnidadMedida:show" }
    methods:  GET

admin_unidad_new:
    path:     /new
    defaults: { _controller: "RedesSivelBundle:UnidadMedida:new" }
    methods:  [GET, POST]

admin_unidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "RedesSivelBundle:UnidadMedida:edit" }
    methods:  [GET, POST]

admin_unidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "RedesSivelBundle:UnidadMedida:delete" }
    methods:  DELETE
